plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

repositories {
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/releases/'
		content {
			includeGroup 'com.terraformersmc'
		}
	}
}

def modVersion = project.mod_version
def archiveBaseName = project.archives_base_name

version = modVersion
group = project.maven_group

base {
	archivesName = archiveBaseName
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modCompileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
}

processResources {
	inputs.property 'version', modVersion

	filesMatching('fabric.mod.json') {
		expand 'version': modVersion
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from('LICENSE') {
		rename { "${it}_${archiveBaseName}" }
	}
}
